"""create buku, favorit, user, dan peminjaman tables

Revision ID: 78b9ed7f7149
Revises: 
Create Date: 2025-05-26 11:27:20.923842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b9ed7f7149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_buku', sa.String(length=255), nullable=False),
    sa.Column('nama_penulis', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buku'))
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('favorit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buku_id'], ['buku.id'], name=op.f('fk_favorit_buku_id_buku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorit'))
    )
    op.create_table('peminjaman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buku_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('returned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['buku_id'], ['buku.id'], name=op.f('fk_peminjaman_buku_id_buku')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peminjaman'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peminjaman')
    op.drop_table('favorit')
    op.drop_table('user')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    op.drop_table('buku')
    # ### end Alembic commands ###
